config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#top'
 
  get '/signup', to: 'users#new'

  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/auth/spotify/callback', to: 'users#spotify'
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    member do
      get 'reservations'
      get 'reservations_list'
      get 'all_reservation'
    end
  end

  resources :stores do
    resources :reservations
  end
  # resources :password_resets, only: [:new, :create, :edit, :update]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  require 'rspotify'
  
  def top
    ENV['ACCEPT_LANGUAGE'] = "ja"
    if params[:search].present?
      @searchartist = RSpotify::Artist.find(params[:search])
    else
      @Top_list = RSpotify::Playlist.find('spotify', '6Mm5y1PZJDdEXl61waypUp')
    end
    
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/top.html.erb
<% provide(:title, "Top") %>
<div class="center jumbotron">
  <h1>カラオケ予約システム</h1>
  <p>カラオケの予約を行えます。</p>
  <% if logged_in? %>
    <%= link_to "予約を行う", stores_path, class: "btn btn-lg btn-info" %>
  <% else %>
  <%= link_to "ユーザー登録", signup_path, class: "btn btn-lg btn-primary" %>
  <% end %>
</div>
<div class="col-md-10 col-md-offset-1">
  <% if @searchartist.present? %>
    <div>
      <div class="center">
        <% if @searchartist.images.any?%>
          <%image = @searchartist.images[1]%>
          <%= image_tag(image["url"])%>
        <% end %>
      </div>
      <h1><%= @searchartist.name %></h1>
      <table class="table table-condensed" id="table-users">
        <th>
          <td>
            <p2>人気曲</p2>
          </td>
        </th>
        <% @searchartist.top_tracks(:JP).each do |song| %>
          <tr>
            <td>
              <% if song.album.images.any? %>
                <%image = song.album.images[2]%>
                <%= image_tag(image["url"])%>
              <% end %>
            </td>
            <td>
              <p2><%= song.name %></p2>
            </td>
            <td><audio src="<%= song.preview_url%>" controls></audio></td>
          </tr>
        <%end%>
      </table>

    </div>
  <%end%>
</div>

<div class="col-md-10 col-md-offset-1">
  <% if @Top_list.present? %>
    <div>
      <h3><%= @Top_list.name %></h3>
      <table class="table table-condensed" id="table-users">
        <% @Top_list.tracks.each_with_index do |song, i| %>
          <tr>
            <td><p><%= i+1 %></p></td>
            <td>
              <% if song.album.images.any? %>
                <%image = song.album.images[2]%>
                <%= image_tag(image["url"])%>
              <% end %>
            </td>
            <td>
              <p2><%= song.name %></p2>
              <p><%= link_to song.artists[0].name, root_path(search: song.artists[0].id), :style=>"color:gray;" %></p>
            </td>
            <td><audio src="<%= song.preview_url%>" controls></audio></td>
          </tr>
        <%end%>
      </table>
    </div>
  <%end%>
</div>