config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#top'
 
  get '/signup', to: 'users#new'

  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/auth/spotify/callback', to: 'users#spotify'
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    member do
      get 'reservations'
      get 'reservations_list'
      get 'all_reservation'
    end
  end

  resources :stores do
    resources :reservations
  end
  # resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :reservations
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :admin_user, only: :destroy
  before_action :set_store, only: [:show]
  before_action :logged_in_user, only: [:index]

  def index
    @stores = Store.all
    
  end

  def show
    
  end

  private

    def set_store
      @store = Store.find(params[:id])
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください。"
        redirect_to login_url
      end
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/index.html.erb
<% provide(:title, 'All Stores') %>
<h1>店舗選択</h1>

<div class="col-md-10 col-md-offset-1">
  <table class="table table-condensed table-hover" id="table-users">
    <thead>
      <tr>
        <th></th>
        <th>店舗</th>
        <th>電話番号</th>
      </tr>
    </thead>

    <% @stores.each do |store| %>
      <tr>
        <td><%= image_tag store.image, class: 'store-index' %></td>
        <td><%= link_to store.name, store_path(store), class: "btn btn-info" %></td>
        <td><%= store.tel %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/stores/show.html.erb
<% provide(:title, @store.name) %>
<div class="col-md-10 col-md-offset-1 center">
  <%= image_tag @store.image, class: "store-show" %>
  <h3><%= @store.name %></h3>
  <p>部屋数: <%= @store.number_of_rooms %></p>
  <p><%= link_to "tel:" + @store.tel, "tel:" + @store.tel %></p>
  <p><%= @store.detail %></p>
  <%= link_to "予約する", store_reservations_path(@store), class: "btn btn-lg btn-info" %>
</div>