config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#top'
 
  get '/signup', to: 'users#new'

  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/auth/spotify/callback', to: 'users#spotify'
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    member do
      get 'reservations'
      get 'reservations_list'
      get 'all_reservation'
    end
  end

  resources :stores do
    resources :reservations
  end
  # resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reservations, dependent: :destroy
  # 「remember_token」という仮想の属性を作成します。
  attr_accessor :remember_token, :reset_token
  before_save { self.email = email.downcase }

  validates :name,  presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true    
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    return false if remember_digest.nil?
  BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :reservations]
  before_action :logged_in_user, only: [:show, :edit, :update, :destroy, :reservations]
  before_action :not_logged_in_user, only: [:new]
  before_action :correct_user, only: [:edit, :update, :reservations]
  before_action :admin_user, only: [:destroy, :all_reservation, :reservations_list, :index]
  before_action :correct_or_admin_user, only: [:show]

  def index
    @users = User.paginate(page: params[:page])
  end
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render :edit      
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end


  def show
  end

  def reservations
    @reservations = Reservation.all.where(user_id: @user.id).where("day >= ?", Date.current)
  end

  def reservations_list
    @stores = Store.all
  end

  def all_reservation
    @reservations = Reservation.all.where("day >= ?", Date.current).where("day < ?", Date.current >> 3).order(day: :desc)
    @stores = Store.all
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def set_user
      @user = User.find(params[:id])
    end

    # ログイン済みのユーザーか確認します。
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください。"
        redirect_to login_url
      end
    end

    def not_logged_in_user
      if logged_in?
        flash[:danger] = "既にログイしてます。"
        redirect_to root_url
      end
    end

    # アクセスしたユーザーが現在ログインしているユーザーか確認します。
    def correct_user
      redirect_to(root_url) unless current_user?(@user)
    end

    # システム管理権限所有かどうか判定します。
    def admin_user
      redirect_to root_url unless current_user.admin?
    end

    def correct_or_admin_user
      redirect_to(root_url) unless current_user?(@user) || current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-info btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/all_reservation.html.erb
<% provide(:title, "全ての予約リスト") %>
<div class="container">
  <div class="row">
    <div class="col-12 text-center">
      <h1>予約リスト</h1>
    </div>
    <div class="col-12 mt-3">
      <%= week_calendar events: @reservations do |date, reservations| %>
        <%= date.day %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>
<h1>ユーザー情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<h1>ユーザー一覧</h1>

<div class="col-md-10 col-md-offset-1">
  <%= will_paginate %>
  <table class="table table-condensed table-hover" id="table-users">
    <thead>
      <tr>
        <th><%= User.human_attribute_name :name %></th>
        <th></th>
      </tr>
    </thead>

    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td>
          <% if current_user.admin? && !current_user?(user) %>
            <%= link_to "削除", user, method: :delete,
                data: { confirm: "削除してよろしいですか？" },
                class: "btn btn-danger" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<h1>ユーザー登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/reservations.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 text-center title">
      <h1>予約詳細画面</h1>
      <% unless @reservations.present? %> 
        <p>現在予約はありません。</p>
      <% end %>
    </div>
    <div class="col-md-10 col-md-offset-1">
      <% @reservations.each do |reservation| %>
        <table class="table table-condensed table-hover reservation-list" id="table-users">
          <tbody>
            <tr>
              <td><%= store_name(reservation.store_id) %></td>
              <td><%= l(reservation.day, format: :default) %></td>
              <td><%= reservation.time %></td>
              <td><%= reservation.use_time %></td>
              <td><%= link_to '予約変更', edit_store_reservation_path(reservation.store_id, reservation.id, reservation), class: "btn btn-info" %></td>
              <td>
                <%= link_to "予約消去", store_reservation_url(reservation.store_id, reservation.id, reservation), method: :delete,
                  data: { confirm: "削除してよろしいですか？" },
                  class: "btn btn-danger" %>
              </td>
            </tr>
          </tbody>
        </table>
      <% end %>
      <div class="col-12 text-right">
        <%= link_to '予約画面に戻る', stores_path %>
      </div>
    </div>
  </div>
  
</div>

app/views/users/reservations_list.html.erb
<% provide(:title, 'All Stores') %>
<h1>今日の予約リスト</h1>

<div class="col-md-10 col-md-offset-1">
  <% @stores.each do |store| %>
    <table class="table table-condensed table-hover" id="table-users">
      <h1><%= store.name %></h1>
      <% reservations = Reservation.all.where(store_id: store.id) %>
      <thead>
        <tr>
          <th>名前</th>
          <th>開始予定時間</th>
          <th>利用時間</th>
        </tr>
      </thead>
      <% reservations.each do |reservation| %>
        <% if reservation.day ==  Date.current %>
          <tbody>
          <tr>
            <td><%= User.find(reservation.user_id).name %></td>
            <td><%= reservation.time %></td>
            <td><%= reservation.use_time %></td>
          </tr>
          </tbody>
        <% end %>
      <% end %>
    </table>
  <% end %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1><%= @user.name %>
<br><%= @user.email %></h1>