config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#top'
 
  get '/signup', to: 'users#new'

  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/auth/spotify/callback', to: 'users#spotify'
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    member do
      get 'reservations'
      get 'reservations_list'
      get 'all_reservation'
    end
  end

  resources :stores do
    resources :reservations
  end
  # resources :password_resets, only: [:new, :create, :edit, :update]
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse head-back navbar-dark">
      <div class="container">
        <%= link_to "カラオケ予約アプリ", root_url, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "トップ", root_path %></li>
            <li><%= link_to "予約", stores_path %></li>
            <% if logged_in? %>
              <li><%= link_to "予約中の部屋", reservations_user_path(current_user) %></li>
              <% if current_user.admin? %>
                <li><%= link_to "今日の予約リスト", reservations_list_user_path(current_user)%></li>
                <li><%= link_to "全予約リスト", all_reservation_user_path(current_user)%></li>
                <li><%= link_to "ユーザ一覧", users_path %></li>
              <% end %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  アカウント <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "ユーザー情報", current_user %></li>
                  <li><%= link_to "ユーザー設定", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "ログアウト", logout_path, method: :delete %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "ログイン", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body class="back">
    <%= render 'layouts/header' %>
    <div class="container back2">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>